[package]
name = "rust_gpu"
version = "0.2.0"
edition = "2021"

[lib]
name = "rust_gpu"
crate-type = ["cdylib"]

[dependencies]
wgpu = "0.17.2"
pollster = "0.3"
bytemuck = { version = "1.14", features = ["derive"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1